voice_group always_sunny_intro
	voice_keysplit voicegroup_piano_keysplit, keysplit_piano
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_piano1_60, 255, 0, 180, 120              @ 1: Piano - Ch1 Vel 60.1 (melody)
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fingered_bass, 255, 102, 76, 145          @ 2: Acoustic Bass - Ch4 Vel 72.4
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_flute, 255, 0, 200, 155                  @ 3: Flute - Ch7 Vel 77.2
	voice_directsound 60, 0, DirectSoundWaveData_drum_and_percussion_kick, 255, 0, 150, 160       @ 4: Kick - Ch10 Vel 80.0
	voice_directsound 60, 0, DirectSoundWaveData_unknown_close_hihat, 255, 150, 50, 160          @ 5: Hi-hat - Ch10 Vel 80.0
	voice_directsound 60, 0, DirectSoundWaveData_sd90_solo_snare, 255, 120, 75, 160             @ 6: Snare - Ch10 Vel 80.0
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_glockenspiel, 255, 140, 70, 140         @ 7: Glockenspiel - Supporting
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_harp, 255, 200, 40, 155                @ 8: Harp - Supporting
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_tubular_bell, 255, 0, 200, 155         @ 9: Tubular bells - Supporting
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 255, 100, 150, 145 @ 10: Choir - Supporting
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 255, 0, 200, 145     @ 11: Choir - Supporting
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_church_organ3_high, 255, 0, 200, 145     @ 12: Church organ - Supporting
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_trumpet_60, 255, 0, 255, 155              @ 13: Warm trumpet - Supporting
	voice_directsound 60, 0, DirectSoundWaveData_unknown_bell, 255, 165, 90, 155                  @ 14: Bell sounds - Supporting
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_string_ensemble_60, 255, 253, 0, 145     @ 15: String ensemble - Supporting
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_detuned_ep1_high, 255, 127, 0, 145 @ 16: Detuned EP - Supporting
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_french_horn_60, 255, 0, 180, 145         @ 17: French horn - Supporting
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 127, 100, 160 @ 18: Orchestra cymbal - Ch10 Vel 80.0
	voice_directsound 60, 0, DirectSoundWaveData_ethnic_flavours_atarigane, 255, 180, 74, 155     @ 19: Atarigane - Supporting
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_pizzicato_strings, 255, 0, 255, 145     @ 20: Pizzicato strings - Supporting
	voice_directsound 60, 0, DirectSoundWaveData_heart_of_asia_gamelan, 255, 165, 90, 155         @ 21: Gamelan - Supporting
	voice_directsound 60, 0, DirectSoundWaveData_unknown_female_voice, 255, 127, 231, 145         @ 22: Female voice - Supporting
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_organ2, 255, 0, 255, 145                 @ 23: Hammond organ - Supporting
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_shakuhachi, 255, 127, 100, 155   @ 24: Shakuhachi - Supporting
	voice_directsound 60, 0, DirectSoundWaveData_ethnic_flavours_kotsuzumi, 255, 180, 74, 160     @ 25: Kotsuzumi - Ch10 Vel 80.0
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_timpani_with_snare, 255, 180, 74, 160   @ 26: Timpani - Ch10 Vel 80.0
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_piano1_72, 255, 0, 180, 120             @ 27: Piano high octave - Ch1 Vel 60.1
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_piano1_84, 255, 0, 180, 120             @ 28: Piano very high octave - Ch1 Vel 60.1
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_string_ensemble_84, 255, 0, 255, 145    @ 29: High strings - Supporting
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 30: Basic voice
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 31: Basic voice
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 32: Basic voice
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 33: Basic voice
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_slap_bass, 255, 253, 0, 145             @ 34: Slap bass - Ch4 Vel 72.4
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_flute, 255, 0, 255, 127                   @ 76: Flute (swing orchestration)
	voice_square_2_alt 60, 0, 1, 2, 3, 1, 8                                                       @ 77: Clarinet simulation
	voice_square_2_alt 60, 0, 2, 1, 1, 3, 11                                                      @ 78: Saxophone simulation  
	voice_square_2_alt 60, 0, 0, 3, 2, 2, 7                                                       @ 79: Muted brass simulation
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 80: Basic voice
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 81: Basic voice
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 82: Basic voice
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 83: Basic voice
	voice_square_2_alt 60, 0, 2, 0, 7, 3, 3                                                       @ 84: Big band brass accent
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 85: Basic voice
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 86: Basic voice
	voice_square_2_alt 60, 0, 1, 1, 2, 3, 0                                                       @ 87: Swing rhythm accent
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_noise_alt 60, 0, 0, 0, 1, 0, 0

