voice_group blue_blood
	voice_keysplit voicegroup_piano_keysplit, keysplit_piano
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_piano1_60, 255, 0, 200, 160                @ 1: Piano - Ch1 Vel 80.0
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fingered_bass, 255, 200, 0, 160           @ 2: Walking bass - Ch2 Vel 80.0
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_trumpet_60, 255, 0, 200, 160              @ 3: Lead trumpet - Ch3 Vel 80.0
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_french_horn_60, 255, 0, 200, 160         @ 4: French horn - Ch4 Vel 80.0
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fretless_bass, 255, 200, 0, 160           @ 5: Fretless bass - Vel 80.0
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_glockenspiel, 255, 140, 70, 160           @ 6: Glockenspiel - Vel 80.0
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_rnd_kick, 255, 0, 150, 160               @ 7: Soft kick - Vel 80.0
	voice_directsound 60, 0, DirectSoundWaveData_unknown_close_hihat, 255, 120, 80, 160         @ 8: Gentle hi-hat - Vel 80.0
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_harp, 255, 200, 40, 160                   @ 9: Harp - Vel 80.0
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_flute, 255, 100, 180, 160               @ 10: Flute - Vel 80.0
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 255, 0, 200, 160     @ 11: Choir - Vel 80.0
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_organ2, 255, 0, 200, 160                  @ 12: Hammond organ - Vel 80.0
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_string_ensemble_60, 255, 0, 255, 160     @ 13: String ensemble - Vel 80.0
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_tubular_bell, 255, 165, 90, 160           @ 14: Tubular bells - Vel 80.0
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_synth_bass, 255, 253, 0, 160             @ 15: Synth bass - Vel 80.0
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_detuned_ep1_low, 255, 127, 0, 160  @ 16: Electric piano - Vel 80.0
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_pizzicato_strings, 255, 0, 255, 160     @ 17: Pizzicato - Vel 80.0
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_orchestra_snare, 255, 150, 124, 160       @ 18: Gentle snare - Vel 80.0
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_tambourine, 255, 130, 95, 160           @ 19: Soft tambourine - Vel 80.0
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_string_ensemble_72, 255, 0, 255, 160     @ 20: Higher strings - Vel 80.0
	voice_directsound 60, 0, DirectSoundWaveData_unknown_female_voice, 255, 127, 231, 160         @ 21: Female voice - Vel 80.0
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_church_organ3_low, 255, 0, 255, 160      @ 22: Church organ - Vel 80.0
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_shakuhachi, 255, 127, 200, 160   @ 23: Shakuhachi - Vel 80.0
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_xylophone, 255, 165, 90, 160             @ 24: Xylophone - Vel 80.0
	voice_directsound 60, 0, DirectSoundWaveData_ethnic_flavours_atarigane, 255, 150, 124, 160     @ 25: Atarigane - Vel 80.0
	voice_directsound 60, 0, DirectSoundWaveData_heart_of_asia_gamelan, 255, 165, 90, 160         @ 26: Gamelan - Vel 80.0
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_piano1_72, 255, 0, 200, 160             @ 27: Piano high octave - Vel 80.0
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_piano1_84, 255, 0, 200, 160             @ 28: Piano very high octave - Vel 80.0
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_string_ensemble_84, 255, 0, 255, 160    @ 29: High strings - Vel 80.0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 30: Basic voice
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 31: Basic voice
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 32: Basic voice
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 33: Basic voice
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_slap_bass, 255, 253, 0, 160             @ 34: Slap bass - Vel 80.0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_flute, 255, 0, 255, 127                   @ 76: Flute (swing orchestration)
	voice_square_2_alt 60, 0, 1, 2, 3, 1, 8                                                       @ 77: Clarinet simulation
	voice_square_2_alt 60, 0, 2, 1, 1, 3, 11                                                      @ 78: Saxophone simulation  
	voice_square_2_alt 60, 0, 0, 3, 2, 2, 7                                                       @ 79: Muted brass simulation
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 80: Basic voice
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 81: Basic voice
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 82: Basic voice
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 83: Basic voice
	voice_square_2_alt 60, 0, 2, 0, 7, 3, 3                                                       @ 84: Big band brass accent
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 85: Basic voice
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                       @ 86: Basic voice
	voice_square_2_alt 60, 0, 1, 1, 2, 3, 0                                                       @ 87: Swing rhythm accent
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_noise_alt 60, 0, 0, 0, 1, 0, 0

