GiantsReach_House1_MapScripts::
	.byte 0

GiantsReach_House1_EventScript_Man::
	msgbox GiantsReach_House1_Text_TravelingIsWonderful, MSGBOX_NPC
	end

GiantsReach_House1_EventScript_Woman::
	msgbox GiantsReach_House1_Text_GoOnAdventure, MSGBOX_NPC
	end

GiantsReach_House1_Text_TravelingIsWonderful:
	.string "When I was younger, I used to roam\n"
	.string "all around.\p"
	.string "From the bustling waterfront to the\n"
	.string "quiet hills nearby!$"

GiantsReach_House1_Text_GoOnAdventure:
	.string "I wish I could go on an adventure\n"
	.string "with some POKéMON.\p"
	.string "Wander through old neighborhoods,\n"
	.string "climb rocky trails,\l"
	.string "cross rushing rivers,\l"
	.string "explore dark caves,\l"
	.string "and sometimes even feel a little\l"
	.string "homesick.\p"
	.string "Traveling like that must be amazing!$"

