PetalburgCity_House2_MapScripts::
	.byte 0

PetalburgCity_House2_EventScript_Woman::
	msgbox PetalburgCity_House2_Text_NormanBecameGymLeader, MSGBOX_NPC
	end

PetalburgCity_House2_EventScript_SchoolKid::
	msgbox PetalburgCity_House2_Text_BattledNormanOnce, MSGBOX_NPC
	end

PetalburgCity_House2_Text_NormanBecameGymLeader:
	.string "JACK became our town’s new\n"
	.string "GYM LEADER a while back.\p"
	.string "He said some family was moving close\n"
	.string "soon. His uh... sister and nephew?\p"
	.string "Honestly, this guy gives me a\n"
	.string "weird feeling.$"

PetalburgCity_House2_Text_BattledNormanOnce:
	.string "I battled JACK once. Or tried to.\p"
	.string "He made me take off my shoes...\p"
	.string "Said it was a 'respect thing'\n"
	.string "for the battlefield.\p"
	.string "I just forfeited. I didn’t like how\n"
	.string "he was looking at me...$"

