gText_Birch_Welcome::
	.string "Hey there, I'm Professor Frank!\n"
	.string "Legally, anyway.\p"
	.string "Got the papers off some guy in a\n"
	.string "Waffle House parking lot.\l"
	.string "Long story.\p"
	.string "This here's the world of Pokémon.\p"
	.string "Some people train 'em, some people\n"
	.string "battle 'em.\p"
	.string "Sometimes I just sell 'em when\n"
	.string "the market's hot.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "$"

gText_Birch_MainSpeech::
	.string "Now this...this is a rat.\n"
	.string "A damn special one, too.\p"
	.string "You're gonna love this.\n"
	.string "Charlie loves rats, big rat guy!\p"
	.string "Spent a whole month livin’ with\n"
	.string "a bunch of ‘em once.\p"
	.string "Eats cheese off the floor with ‘em.\n"
	.string "Reads bedtime stories to 'em.\p"
	.string "He even claimed they taught him\n"
	.string "another language or some shit like that.\p"
	.string "He still kills 'em sometimes though,\n"
	.string "it's hilarious!\p"
	.string "Now, you're gonna be part of that dream.\p"
	.string "I'm giving you the chance to\n"
	.string "take this rodent and go beat\l"
	.string "the crap outta other kids’ pets.\p"
	.string "You're not saving the world or anything,\n"
	.string "but you might be king of Trashburg,\l"
	.string "and that’s somethin’.\p"
	.string "$"


gText_Birch_YourePlayer::
	.string "$"

gText_Birch_HaveYouPlayedPokemonBefore::
	.string "Have you played Pokémon before?$"

gText_Birch_HaventPlayedPokemon::
	.string "No worries, I got you covered.\n"	
	.string "It's a game where you catch\l"
	.string "and train these little monsters.\p"
	.string "Then you use them to battle other\n"
	.string "people's Pokémon.\p"
	.string "It's kinda like being a pet wrestler.\p"
	.string "It's a lot of fun, and I think\n"
	.string "you're gonna love it!$"

gText_Birch_AreYouReady::
	.string "Oh yeah,\n"
	.string "you're Charlie now.\p"
	.string "Just lean into it.\n"
	.string "The rats already know your scent.\p"
	.string "The real Charlie couldn't make it.\n"
	.string "Somethin' about glue fumes.\p"
	.string "Join us.\p"
	.string "Accept the rats.\p"
	.string "Accept the trash.\p"
	.string "Accept the destiny.\p"
	.string "Let's go make some chaos.\p"
	.string "$"

gText_Birch_LetsGetIntoIt::
	.string "Alright, let's get into it!\n"
	.string "Go out there and make me proud,\l"
	.string "Charlie!\p"
	.string "And remember, rats are friends,\n"
	.string "not food.\p"
	.string "Accept the rats.\p"
	.string "Accept the trash.\p"
	.string "Accept the destiny.\p"
	.string "Let's go make some chaos.$"

gText_Birch_HavePlayedPokemon::
	.string "Awesome!\n"
	.string "I'm glad you aren't new to this.\p"
	.string "This is gonna be a little different.$"

gText_Birch_NuzlockeChallenge::
	.string "Since you're not new, I got a\n"
	.string "question for ya.\p"
	.string "I know of something called a\n"
	.string "Nuzlocke challenge.\p"
	.string "Means you can only catch the first\n"
	.string "Pokémon you see in each area.\p"
	.string "If it faints, it's dead to you.\p"
	.string "You gotta release it or put it in\n"
	.string "a box and never use it again.\p"
	.string "Makes things way more intense.\p"
	.string "You in?$"

gText_Birch_NoNuzlocke::
	.string "No worries, we can skip the Nuzlocke\n"
	.string "challenge.\p"
	.string "You can play the game normally.\p"
	.string "If you ever want to give it a go,\n"
	.string "you have to start a new game.$"

gText_Birch_YesNuzlocke::
	.string "Hell yeah!\n"
	.string "This is gonna be awesome.\p"
	.string "Was afraid I was dealing with a\n"
	.string "little chicken there for a second.\p"
	.string "I'm ready to take on the challenge.\p"
	.string "Just remember, if a Pokémon\n"
	.string "faints, it's gone for good.$"

gText_Birch_Farewell::
	.string "Alright, that's enough talk.\n"
	.string "Time to get started!\p"
	.string "Your adventure awaits!$"
