gText_HowMayIServeYou::
	.string "Yo.\p"
	.string "You buyin’ somethin' or what?$"

gText_PleaseComeAgain::
	.string "Yeah, yeah. Come back and\n"
	.string "spend some cash...$"

gText_PlayerWhatCanIDoForYou::
	.string "Hey Charlie, you're back.\p"
	.string "Alright, what do ya need this time?$"

gText_MyBrotherInOldale::
	.string "Oh.. Hey there {PLAYER}.\p"
	.string "My brother down in OLD SCUMPORT\n"
	.string "told me he saw you the other day.\p"
	.string "Said you barely spent a dime in his\n"
	.string "shop.\p"
	.string "What’s the deal, huh?\p"
	.string "You tryin’ to stiff the family or\n"
	.string "somethin'?\p"
	.string "You better start droppin’ some cash,\n"
	.string "or I’m gonna have to send someone\l"
	.string "over to collect!$"

