gText_WouldYouLikeToRestYourPkmn::
	.string "WAITRESS: Ugh. Hi, Charlie.\p"
	.string "This is the Pokémon Center.\n"
	.string "We heal stuff.\p"
	.string "You want me to fix your weird little\n"
	.string "POKéMON?$"

gText_IllTakeYourPkmn::
	.string "Fine. Hand them over.\n"
	.string "I’ll do it. Just… stop staring at me.$"

gText_RestoredPkmnToFullHealth::
	.string "There. They’re better.\p"
	.string "No, that doesn't mean we’re friends.\n"
	.string "Please leave me alone for a while.\p"
	.string "$"

gText_WeHopeToSeeYouAgain::
	.string "Actually,\n" 
	.string "I hope I don’t see you again.$"

gText_WelcomeCutShort::
	.string "WAITRESS: Charlie, seriously?\n"
	.string "Again?\p"
	.string "What do you even do to them?$"

gText_NoticesGoldCard::
	.string "WAITRESS: Ugh..Hey Char...\p"
	.string "Whoa… wait.\n"
	.string "Is that a… is that a Gold Card?\p"
	.string "It’s… actually kinda impressive,\n"
	.string "Charlie.\p"
	.string "The shimmer… the stars…\n"
	.string "It’s, like… really gold.\p"
	.string "I mean, I’ve seen losers with\n"
	.string "Silver Cards..but you?\l"
	.string "You have a Gold one?\p"
	.string "Okay…\n"
	.string "Look, just let me heal your Pokémon.\l"
	.string "It’s not a big deal or anything.\p"
	.string "I’m just saying…\n"
	.string "Gold looks… good on you.$"

gText_YouWantTheUsual::
	.string "WAITRESS: Oh, Charlie.\n"
	.string "Same nonsense as usual?\p"
	.string "Of course it is.$"

gText_IllTakeYourPkmn2::
	.string "Yep. Give ‘em here.\n"
	.string "Can’t believe I’m still doing this\l"
	.string "for you.$"

gText_ThankYouForWaiting::
	.string "Thanks for waiting, I guess.\n"
	.string "I mean, I didn’t ask you to, but…$"

gText_WeHopeToSeeYouAgain2::
	.string "You’re gonna come back in, like\n"
	.string "10 minutes, huh.\p"
	.string "Great.$"
