gText_WouldYouLikeToRestYourPkmn::
	.string "WAITRESS: Ugh. Hi, Charlie.\p"
	.string "You want me to heal your weird little\n"
	.string "POKéMON?$"

gText_IllTakeYourPkmn::
	.string "WAITRESS: Fine. Hand them over.\p"
	.string "And seriously, stop staring at me like\n"
	.string "that...$"

gText_RestoredPkmnToFullHealth::
	.string "WAITRESS: There. They’re better.\p"
	.string "No, that doesn't mean we’re friends.\p"
	.string "$"

gText_WeHopeToSeeYouAgain::
	.string "Please leave me alone for a while.$"

gText_WelcomeCutShort::
	.string "WAITRESS: Charlie, seriously?\n"
	.string "Again?\p"
	.string "What do you even do to them?$"

gText_NoticesGoldCard::
	.string "WAITRESS: Ugh..Hey Char...\p"
	.string "Whoa… wait.\n"
	.string "Is that a… is that a Gold Card?\p"
	.string "It’s… actually kinda impressive,\n"
	.string "Charlie.\p"
	.string "The shimmer… the stars…\n"
	.string "It’s, like… really gold.\p"
	.string "I mean, I’ve seen losers with\n"
	.string "Silver Cards..but you?\l"
	.string "You have a Gold one?\p"
	.string "Okay…\n"
	.string "Look, just let me heal your Pokémon.\l"
	.string "It’s not a big deal or anything.\p"
	.string "I’m just saying…\n"
	.string "Gold looks… good on you.$"

gText_YouWantTheUsual::
	.string "WAITRESS: Oh, Charlie.\n"
	.string "Same nonsense as usual?\p"
	.string "Of course it is.$"

gText_IllTakeYourPkmn2::
	.string "WAITRESS: Yeah, yeah, give ‘em here.\n"
	.string "Can’t believe I’m still doing this.$"

gText_ThankYouForWaiting::
	.string "WAITRESS: Thanks for waiting, I guess.\n"
	.string "Not like I asked you to or anything.$"

gText_WeHopeToSeeYouAgain2::
	.string "WAITRESS: You’re gonna come back in\n"
	.string "like 10 minutes, huh?\p"
	.string "Great...$"
