gFrankDexRatingText_AreYouCurious::
	.string "PROF. FRANK: Ah, {PLAYER}{KUN}!\p"
	.string "Are you curious about how your\n"
	.string "POKéDEX is coming along?$"

gFrankDexRatingText_Cancel::
	.string "Hm? Oh, you haven't caught enough\n"
	.string "POKéMON to make it worthwhile.$"

gFrankDexRatingText_SoYouveSeenAndCaught::
	.string "Hmhm…\p"
	.string "So, you've seen {STR_VAR_1} POKéMON,\n"
	.string "and you've caught {STR_VAR_2} POKéMON…$"

gFrankDexRatingText_LessThan10::
	.string "Go into grassy areas more and look\n"
	.string "for POKéMON more carefully.$"

gFrankDexRatingText_LessThan20::
	.string "I guess you're getting the hang\n"
	.string "of it. But, it gets harder from here.$"

gFrankDexRatingText_LessThan30::
	.string "Some POKéMON only appear in\n"
	.string "certain areas.\l"
	.string "You must be persistent.$"

gFrankDexRatingText_LessThan40::
	.string "Well, it could use more quantity,\n"
	.string "but this is looking more like\l"
	.string "a POKéDEX now.$"

gFrankDexRatingText_LessThan50::
	.string "This is coming along pretty good.\n"
	.string "Keep up the effort.$"

gFrankDexRatingText_LessThan60::
	.string "Are you using any RODS?\n"
	.string "There are many POKéMON in the sea.$"

gFrankDexRatingText_LessThan70::
	.string "Instead of just catching POKéMON,\n"
	.string "how about making them evolve, too?$"

gFrankDexRatingText_LessThan80::
	.string "This is going to be a fantastic\n"
	.string "POKéDEX.\l"
	.string "That's the feeling I'm getting.$"

gFrankDexRatingText_LessThan90::
	.string "You've collected this many…\n"
	.string "Your talent is remarkable!$"

gFrankDexRatingText_LessThan100::
	.string "Have you visited the SAFARI ZONE?\p"
	.string "I hear there are some POKéMON that\n"
	.string "can only be caught there.$"

gFrankDexRatingText_LessThan110::
	.string "You've finally reached\n"
	.string "the 100-kind mark.\p"
	.string "This is an impressive POKéDEX!$"

gFrankDexRatingText_LessThan120::
	.string "There might be POKéMON that can be\n"
	.string "found using ROCK SMASH.$"

gFrankDexRatingText_LessThan130::
	.string "You should get some more POKéMON\n"
	.string "by trading with others.$"

gFrankDexRatingText_LessThan140::
	.string "I've heard of POKéMON that evolve\n"
	.string "when they come to fully love their\l"
	.string "TRAINERS.$"

gFrankDexRatingText_LessThan150::
	.string "I had no idea that there were so\n"
	.string "many POKéMON species in the HOENN\l"
	.string "region.$"

gFrankDexRatingText_LessThan160::
	.string "On occasion, some POKéMON appear\n"
	.string "in large numbers like outbreaks.\p"
	.string "Don't miss opportunities like\n"
	.string "those.$"

gFrankDexRatingText_LessThan170::
	.string "One can get a very good idea about\n"
	.string "the POKéMON of the HOENN region\l"
	.string "by looking through your POKéDEX.$"

gFrankDexRatingText_LessThan180::
	.string "I would say you already qualify as\n"
	.string "a POKéMON PROFESSOR, and a good\l"
	.string "one, too!$"

gFrankDexRatingText_LessThan190::
	.string "With a POKéDEX this complete,\n"
	.string "you're a real professional at this!$"

gFrankDexRatingText_LessThan200::
	.string "You're very close to completing\n"
	.string "this POKéDEX.\l"
	.string "I can feel it in my bones!$"

gFrankDexRatingText_DexCompleted::
	.string "Congratulations!\n"
	.string "Your POKéDEX is complete!$"

gFrankDexRatingText_OnANationwideBasis::
	.string "Hmhm…\n"
	.string "On a nationwide basis…\p"
	.string "You've seen {STR_VAR_1} POKéMON,\n"
	.string "and you've caught {STR_VAR_2} POKéMON…$"
