OldaleTown_House1_MapScripts::
	.byte 0

OldaleTown_House1_EventScript_Woman::
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
	end

OldaleTown_House1_Text_LeftPokemonGoesOutFirst:
	.string "Hey, pro tip from a seasoned battler:\p"
	.string "The first 'mon in line jumps out first.\p"
	.string "Don’t put your weakest freak up\n"
	.string "front unless you're into losing.\p"
	.string "I like to call it 'lead with chaos'.\n"
	.string "Really sets the tone.$"

